name: Linters

on: pull_request

env:
  GITHUB_BASE_REF: ${{ github.base_ref }}

jobs:
  run-linters:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Correct NodeJS version
      shell: bash -l {0}
      run: |
        nvm install
        nvm use

    - name: Run npm install
      run: npm i

    - name: Fetch target branch
      run: git fetch -n origin ${GITHUB_BASE_REF}

    - name: Run eslint linter
      if: ${{ always() }}
      run: git diff --diff-filter=d origin/${GITHUB_BASE_REF} --name-only -- '*.ts' | xargs -r  npx eslint --max-warnings=0 . -c .eslintrc.js
